# Generated by Django 2.2.3 on 2019-07-29 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonDatesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('commondatesmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comment.CommonDatesModel')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
            bases=('comment.commondatesmodel',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('commondatesmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comment.CommonDatesModel')),
                ('amount', models.FloatField(null=True)),
                ('products', models.ManyToManyField(to='comment.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('comment.commondatesmodel',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commondatesmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comment.CommonDatesModel')),
                ('comment_text', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Order')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comment.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=('comment.commondatesmodel',),
        ),
    ]
